git remote add -f vim-pathogen git@github.com:tpope/vim-pathogen.git
git remote add -f matchit git@github.com:tmhedberg/matchit.git
git remote add -f vim-speeddating git@github.com:tpope/vim-speeddating.git
git remote add -f vim-surround git@github.com:tpope/vim-surround.git
git remote add -f vim-repeat git@github.com:tpope/vim-repeat.git
git remote add -f vim-misc git@github.com:xolox/vim-misc.git
git remote add -f vim-easytags vim-easytags
git remote add -f vim-reload git@github.com:xolox/vim-reload.git
git remote add -f tagbar git@github.com:majutsushi/tagbar.git
git remote add -f tcomment_vim git@github.com:tomtom/tcomment_vim.git
git remote add -f vim-hilinks git@github.com:kergoth/vim-hilinks.git
git remote add -f vim-ps1 git@github.com:PProvost/vim-ps1.git
git remote add -f syntastic git@github.com:scrooloose/syntastic.git
git remote add -f tabular git@github.com:godlygeek/tabular.git
git remote add -f vim-hoogle git@github.com:Twinside/vim-hoogle.git
git remote add -f previm git@github.com:kannokanno/previm.git
git remote add -f open-browser git@github.com:tyru/open-browser.vim.git
git remote add -f vim-syntax-haskell-cabal git@github.com:Twinside/vim-syntax-haskell-cabal.git
git remote add -f CamelCaseMotion git@github.com:bkad/CamelCaseMotion.git
git remote add -f vim-fugitive git@github.com:tpope/vim-fugitive
git remote add -f vim-easy-align git@github.com:junegunn/vim-easy-align
git remote add -f vim-pandoc-syntax git@github.com:vim-pandoc/vim-pandoc-syntax
