git subtree pull --prefix bundle/vim-pathogen git@github.com:tpope/vim-pathogen.git master --squash
git subtree pull --prefix bundle/matchit git@github.com:tmhedberg/matchit.git master --squash
git subtree pull --prefix bundle/vim-speeddating git@github.com:tpope/vim-speeddating.git master --squash
git subtree pull --prefix bundle/vim-surround git@github.com:tpope/vim-surround.git master --squash
git subtree pull --prefix bundle/vim-repeat git@github.com:tpope/vim-repeat.git master --squash
git subtree pull --prefix bundle/vim-misc git@github.com:xolox/vim-misc.git master --squash
git subtree pull --prefix bundle/vim-easytags git@github.com:xolox/vim-easytags.git master --squash
git subtree pull --prefix bundle/vim-reload git@github.com:xolox/vim-reload.git master --squash
git subtree pull --prefix bundle/tagbar git@github.com:majutsushi/tagbar.git master --squash
git subtree pull --prefix bundle/ultisnips git@github.com:SirVer/ultisnips.git master --squash
git subtree pull --prefix bundle/vim-snippets git@github.com:honza/vim-snippets.git master --squash
git subtree pull --prefix bundle/tcomment_vim git@github.com:tomtom/tcomment_vim.git master --squash
git subtree pull --prefix bundle/vim-hilinks git@github.com:kergoth/vim-hilinks.git master --squash
git subtree pull --prefix bundle/vim-ps1 git@github.com:PProvost/vim-ps1.git master --squash
git subtree pull --prefix bundle/syntastic git@github.com:scrooloose/syntastic.git master --squash
git subtree pull --prefix bundle/tabular git@github.com:godlygeek/tabular.git master --squash
git subtree pull --prefix bundle/vim-hoogle git@github.com:Twinside/vim-hoogle.git master --squash
git subtree pull --prefix bundle/previm git@github.com:kannokanno/previm.git master --squash
git subtree pull --prefix bundle/open-browser git@github.com:tyru/open-browser.vim.git master --squash
git subtree pull --prefix bundle/vim-syntax-haskell-cabal git@github.com:Twinside/vim-syntax-haskell-cabal.git master --squash
git subtree pull --prefix bundle/CamelCaseMotion git@github.com:bkad/CamelCaseMotion.git master --squash
