git subtree pull --prefix bundle/vim-pathogen vim-pathogen master --squash
git subtree pull --prefix bundle/matchit matchit master --squash
git subtree pull --prefix bundle/vim-speeddating vim-speeddating master --squash
git subtree pull --prefix bundle/vim-surround vim-surround master --squash
git subtree pull --prefix bundle/vim-repeat vim-repeat master --squash
git subtree pull --prefix bundle/vim-misc vim-misc master --squash
git subtree pull --prefix bundle/vim-easytags vim-easytags master --squash
git subtree pull --prefix bundle/vim-reload vim-reload master --squash
git subtree pull --prefix bundle/tagbar tagbar master --squash
git subtree pull --prefix bundle/tcomment_vim tcomment_vim master --squash
git subtree pull --prefix bundle/vim-hilinks vim-hilinks master --squash
git subtree pull --prefix bundle/vim-ps1 vim-ps1 master --squash
git subtree pull --prefix bundle/syntastic syntastic master --squash
git subtree pull --prefix bundle/tabular tabular master --squash
git subtree pull --prefix bundle/vim-hoogle vim-hoogle master --squash
git subtree pull --prefix bundle/previm previm master --squash
git subtree pull --prefix bundle/open-browser open-browser master --squash
git subtree pull --prefix bundle/vim-syntax-haskell-cabal vim-syntax-haskell-cabal master --squash
git subtree pull --prefix bundle/CamelCaseMotion CamelCaseMotion master --squash
git subtree pull --prefix bundle/vim-fugitive vim-fugitive master --squash
git subtree pull --prefix bundle/vim-easy-align vim-easy-align master --squash
